export const customerDummy = [
  {
    id: 16,
    createdAt: "2026-03-10T11:27:41.8128199",
    requestId: 1,
    code: "32929",
    ownersName: "JACINTHA PONCE",
    registrationStatus: "Under review",
    ownersAddress: {
      houseNumber: "15",
      streetName: "GOV SISON ST",
      barangayName: "POBLACION",
      city: "LINGAYEN",
      province: "PANGASINAN",
    },
    phoneNumber: "9999",
    emailAddress: "",
    dateOfBirth: "2026-03-10",
    tinNumber: "111-111-111-000",
    businessName: "RCS SUPERMARKET MABINI",
    origin: "Direct",
    businessAddress: {
      houseNumber: "15",
      streetName: "GOV SISON ST",
      barangayName: "POBLACION",
      city: "LINGAYEN",
      province: "PANGASINAN",
    },
    distriType: "Institutional",
    authorizedRepresentative: "",
    authorizedRepresentativePosition: "",
    subTerritoryId: 1,
    subTerritoryName: "TDO - NORTH LUZON",
    priceModeId: 0,
    priceModeName: null,
    longitude: null,
    latitude: null,
    requestor: null,
    requestorMobileNumber: null,
    requestorEmailAddress: null,
    terms: null,
    currentApprover: null,
    currentApproverPhoneNumber: null,
    nextApprover: null,
    nextApproverPhoneNumber: null,
    isVariableDiscount: null,
    fixedDiscount: 10,
  },
];
